export const categoryPresets = {
  skip: [
    "Skip IGT",
    "Skip EGT",
    "Skipless IGT",
    "Skipless EGT",
    "R15 Skip",
    "R15 Skipless",
    "R6 Skip",
    "R6 Skipless",
    "Glitch",
  ],

  skipless: [
    "Skipless IGT",
    "Skipless EGT",
    "R15 Skipless",
    "R6 Skipless",
    "Glitch",
  ],

  rthroskip: [
    "Skip IGT",
    "Skip EGT",
    "Skipless IGT",
    "Skipless EGT",
    "R15 Skipless",
    "R6 Skipless",
    "Glitch",
  ],

  r15skip: [
    "Skip IGT",
    "Skip EGT",
    "Skipless IGT",
    "Skipless EGT",
    "R15 Skip",
    "R15 Skipless",
    "R6 Skipless",
    "Glitch",
  ],

  r6skip: [
    "Skip IGT",
    "Skip EGT",
    "Skipless IGT",
    "Skipless EGT",
    "R15 Skipless",
    "R6 Skip",
    "R6 Skipless",
    "Glitch",
  ],
}

export const mapCategoryPresets: Record<string, keyof typeof categoryPresets> = {
  reflection: "skipless",
  "magma-cavern": "skipless",
  skyscrapers: "skip",
  legacy: "skipless",
  "acid-realm": "skipless",
  "snowy-slopes": "skipless",
  heights: "skip",
  dunes: "skipless",
  frozen: "rthroskip",
  "tropical-dash": "skipless",
  "crystal-mine": "skip",
  "laser-tag": "rthroskip",
  canyon: "rthroskip",
  "grassy-mountain": "skipless",
  "tropical-islands": "skipless",
  "dragons-lair": "r15skip",
  "island-route": "rthroskip",
  "mystic-alps": "skip",
  "river-of-ice": "skipless",
  "the-orion-disaster": "rthroskip",
  swamp: "skipless",
  "pastel-valley": "skip",
  "enchanted-forest": "rthroskip",
  "ancient-tomb": "skipless",
  floatroads: "skipless",
  "fuyu-village": "skipless",
  candyland: "skipless",
  ravine: "skip",
  "northern-cliffs": "skip",
  "honeycomb-run": "skip",
  heist: "rthroskip",
  "mystical-gorge": "r15skip",
  "twilight-lagoon": "skip",
  "autumn-woodlands": "skip",
  "western-bluffs": "skip",
  "winter-cove": "r15skip",
  "cavern-of-darkness": "r15skip",
  "the-emerald-isle": "skip",
  "melodical-fantasy": "r15skip",
  taiga: "skipless",
  "jurassic-coast": "skip",
  "clockwork-colosseum": "skip",
  "frosted-fortress": "skip",
  "night-terrors": "skip",
  "disaster-valley": "skip",
  "the-realm-between": "skip",
  "cosmic-cliffside": "skip",
  shipwrecked: "skip",
}

export function getCategoriesForMap(map: string) {
  const preset = mapCategoryPresets[map] ?? "skip"

  return categoryPresets[preset]
}