export const maps = [
  "Reflection",
  "Magma Cavern",
  "Skyscrapers",
  "Legacy",
  "Acid Realm",
  "Snowy Slopes",
  "Heights",
  "Dunes",
  "Frozen",
  "Tropical Dash",
  "Crystal Mine",
  "Laser Tag",
  "Canyon",
  "Grassy Mountain",
  "Tropical Islands",
  "Dragons Lair",
  "Island Route",
  "Mystic Alps",
  "River of Ice",
  "The Orion Disaster",
  "Swamp",
  "Pastel Valley",
  "Enchanted Forest",
  "Ancient Tomb",
  "Floatroads",
  "Fuyu Village",
  "Candyland",
  "Ravine",
  "Northern Cliffs",
  "Honeycomb Run",
  "Heist",
  "Mystical Gorge",
  "Twilight Lagoon",
  "Autumn Woodlands",
  "Western Bluffs",
  "Winter Cove",
  "Cavern of Darkness",
  "The Emerald Isle",
  "Melodical Fantasy",
  "Taiga",
  "Jurassic Coast",
  "Clockwork Colosseum",
  "Frosted Fortress",
  "Night Terrors",
  "Disaster Valley",
  "The Realm Between",
  "Cosmic Cliffside",
  "Shipwrecked",
]